### ISSUE TITLE
RoadMap

### ISSUE THREAD

**Issue by Adoni5** [Adoni5/readfish-tools#1]
A map of roads

### Goal
Open API - so this can be imported, and used modularly - I.e generate a flowcell and get coords.

- Parsing
    - [ ] Parse the toml into a conf the same way as readifsh
    - [ ] Implement the same methods as readfish
        - [ ] Merge intervals
        - [ ] Targets
        - [ ] Barcodes
        - [ ] Regions
        - [ ] Get coords
    - [ ] Open and parse a BAM file
    - [ ] find out do they have the Barcode in the tag for FASTQ

- Function
    - [ ] Demultiplex reads/BAMS based on Region or Barcode
    - [ ] Summarise stats
         - [ ] General stats about the run/region - N50 Mean etc.
         - [ ] If BAM, sort mapping to contig/on target/off target
